### ISSUE TITLE
Dependency issue (?)

### ISSUE THREAD

**Issue by IvanPalm** [remotesensinginfo/arcsi#2]
Hi,

I'm following the intro tutorial you kindly provided to get started with ARCSI
https://www.arcsi.remotesensing.info/tutorials/ARCSI_Intro_Tutorial_compress.pdf

I'm pretty sure that all libraries are installed, but there seems to be some issues with the libpoppler.so.71.

ON TERMINAL

```
(arcsi_env) ivan@thinkpad-p53: ~/miniconda3/envs/arcsi_env/bin$ conda install -c conda-forge arcsi python-fmask tuiview scikit-learn matplotlib h5py
Collecting package metadata (current_repodata.json): done
Solving environment: done

All requested packages already installed.

(arcsi_env) ivan@thinkpad-p53: ~/miniconda3/envs/arcsi_env/bin$ arcsi.py --version
Traceback (most recent call last):
  File "/home/ivan/miniconda3/envs/arcsi_env/bin/arcsi.py", line 56, in <module>
    import arcsilib.arcsirun
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/arcsilib/arcsirun.py", line 61, in <module>
    from arcsilib.arcsiutils import ARCSISensorFactory
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/arcsilib/arcsiutils.py", line 46, in <module>
    import osgeo.gdal as gdal
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
(arcsi_env) ivan@thinkpad-p53: ~/miniconda3/envs/arcsi_env/bin$ tuiview
Traceback (most recent call last):
  File "/home/ivan/miniconda3/envs/arcsi_env/bin/tuiview", line 4, in <module>
    import tuiview.viewerapplication
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/tuiview/viewerapplication.py", line 27, in <module>
    from . import geolinkedviewers
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/tuiview/geolinkedviewers.py", line 27, in <module>
    from . import viewerwindow
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/tuiview/viewerwindow.py", line 39, in <module>
    from . import viewerwidget
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/tuiview/viewerwidget.py", line 31, in <module>
    from . import viewerlayers
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/tuiview/viewerlayers.py", line 27, in <module>
    from osgeo import gdal
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ivan/miniconda3/envs/arcsi_env/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
(arcsi_env) ivan@thinkpad-p53: ~/miniconda3/envs/arcsi_env/bin$ 
```
Has anyone had this issue? If so, has anyone found a solution to it?

Thanks in advance for your kind support!

**Comment by IvanPalm** [comment]
The issue with libpoppler.so.71 was related to some incompatibility between gdal and poppler because they were downloaded by two different channels.

The ARCSI tutorial I linked in my question recommends to select python=3.5 while creating the virtual environment with conda, so I made a couple of attempts with different python versions and channels. Eventually I simply used the latest python version and let conda installing the latest version available in conda-forge for all the required packages. The dependency/incompatibility issue is now solved.
